# This file is generated by scripts/aurpkg. Do not edit by hand.

pkgname=dotenv-sync-bin
pkgver=1.2.3
pkgrel=1
pkgdesc='Keep .env files in sync with .env.example and Bitwarden secrets'
arch=('x86_64' 'aarch64')
url='https://github.com/mikeboiko/dotenv-sync'
license=('MIT')
options=('!strip')
provides=('dotenv-sync')
conflicts=('dotenv-sync' 'dotenv-sync-git')

source=("LICENSE::https://raw.githubusercontent.com/mikeboiko/dotenv-sync/v${pkgver}/LICENSE" "README.md::https://raw.githubusercontent.com/mikeboiko/dotenv-sync/v${pkgver}/README.md")
sha256sums=('cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc' 'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd')
source_x86_64=("${pkgname}-${pkgver}-x86_64.tar.gz::https://github.com/mikeboiko/dotenv-sync/releases/download/v${pkgver}/ds_v${pkgver}_linux_amd64.tar.gz")
sha256sums_x86_64=('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
source_aarch64=("${pkgname}-${pkgver}-aarch64.tar.gz::https://github.com/mikeboiko/dotenv-sync/releases/download/v${pkgver}/ds_v${pkgver}_linux_arm64.tar.gz")
sha256sums_aarch64=('bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb')

package() {
	install -Dm755 "${srcdir}/ds" "${pkgdir}/usr/bin/ds"
	install -Dm644 "${srcdir}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	install -Dm644 "${srcdir}/README.md" "${pkgdir}/usr/share/doc/${pkgname}/README.md"
}
