package aur

import (
	"encoding/hex"
	"fmt"
	"strings"

	"dotenv-sync/internal/release"
)

const (
	dotenvSyncBinPackageName = "dotenv-sync-bin"
	dotenvSyncDescription    = "Keep .env files in sync with .env.example and Bitwarden secrets"
	dotenvSyncURL            = "https://github.com/mikeboiko/dotenv-sync"
	dotenvSyncRawURL         = "https://raw.githubusercontent.com/mikeboiko/dotenv-sync"
)

type CommonSource struct {
	Name   string
	SHA256 string
}

type Target struct {
	Arch        string
	LinuxGOARCH string
	SHA256      string
}

type DotenvSyncBin struct {
	VersionTag    string
	PkgRel        int
	CommonSources []CommonSource
	Targets       []Target
}

func NewDotenvSyncBin(versionTag string, pkgRel int, licenseSHA256, readmeSHA256, amd64SHA256, arm64SHA256 string) (DotenvSyncBin, error) {
	versionTag = strings.TrimSpace(versionTag)
	if _, ok := release.Parse(versionTag); !ok {
		return DotenvSyncBin{}, fmt.Errorf("invalid release tag %q", versionTag)
	}
	if pkgRel < 1 {
		return DotenvSyncBin{}, fmt.Errorf("pkgrel must be at least 1, got %d", pkgRel)
	}
	commonSources := []CommonSource{
		{Name: "LICENSE", SHA256: normalizeSHA256(licenseSHA256)},
		{Name: "README.md", SHA256: normalizeSHA256(readmeSHA256)},
	}
	targets := []Target{
		{Arch: "x86_64", LinuxGOARCH: "amd64", SHA256: normalizeSHA256(amd64SHA256)},
		{Arch: "aarch64", LinuxGOARCH: "arm64", SHA256: normalizeSHA256(arm64SHA256)},
	}
	for _, source := range commonSources {
		if err := validateSHA256(source.SHA256); err != nil {
			return DotenvSyncBin{}, fmt.Errorf("%s checksum: %w", source.Name, err)
		}
	}
	for _, target := range targets {
		if err := validateSHA256(target.SHA256); err != nil {
			return DotenvSyncBin{}, fmt.Errorf("%s checksum: %w", target.Arch, err)
		}
	}
	return DotenvSyncBin{
		VersionTag:    versionTag,
		PkgRel:        pkgRel,
		CommonSources: commonSources,
		Targets:       targets,
	}, nil
}

func (p DotenvSyncBin) PKGBUILD() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# This file is generated by scripts/aurpkg. Do not edit by hand.\n\n")
	fmt.Fprintf(&b, "pkgname=%s\n", dotenvSyncBinPackageName)
	fmt.Fprintf(&b, "pkgver=%s\n", p.PkgVer())
	fmt.Fprintf(&b, "pkgrel=%d\n", p.PkgRel)
	fmt.Fprintf(&b, "pkgdesc='%s'\n", dotenvSyncDescription)
	fmt.Fprintf(&b, "arch=('x86_64' 'aarch64')\n")
	fmt.Fprintf(&b, "url='%s'\n", dotenvSyncURL)
	fmt.Fprintf(&b, "license=('MIT')\n")
	fmt.Fprintf(&b, "options=('!strip')\n")
	fmt.Fprintf(&b, "provides=('dotenv-sync')\n")
	fmt.Fprintf(&b, "conflicts=('dotenv-sync' 'dotenv-sync-git')\n\n")
	fmt.Fprintf(&b, "source=(")
	for index, source := range p.CommonSources {
		if index > 0 {
			fmt.Fprintf(&b, " ")
		}
		fmt.Fprintf(&b, "\"%s::%s\"", source.Name, p.templateTaggedFileURL(source.Name))
	}
	fmt.Fprintf(&b, ")\n")
	fmt.Fprintf(&b, "sha256sums=(")
	for index, source := range p.CommonSources {
		if index > 0 {
			fmt.Fprintf(&b, " ")
		}
		fmt.Fprintf(&b, "'%s'", source.SHA256)
	}
	fmt.Fprintf(&b, ")\n")
	for _, target := range p.Targets {
		fmt.Fprintf(&b, "source_%s=(\"${pkgname}-${pkgver}-%s.tar.gz::%s\")\n", target.Arch, target.Arch, p.templateSourceURL(target))
		fmt.Fprintf(&b, "sha256sums_%s=('%s')\n", target.Arch, target.SHA256)
	}
	fmt.Fprintf(&b, "\npackage() {\n")
	fmt.Fprintf(&b, "\tinstall -Dm755 \"${srcdir}/ds\" \"${pkgdir}/usr/bin/ds\"\n")
	fmt.Fprintf(&b, "\tinstall -Dm644 \"${srcdir}/LICENSE\" \"${pkgdir}/usr/share/licenses/${pkgname}/LICENSE\"\n")
	fmt.Fprintf(&b, "\tinstall -Dm644 \"${srcdir}/README.md\" \"${pkgdir}/usr/share/doc/${pkgname}/README.md\"\n")
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

func (p DotenvSyncBin) SRCINFO() string {
	var b strings.Builder
	fmt.Fprintf(&b, "pkgbase = %s\n", dotenvSyncBinPackageName)
	fmt.Fprintf(&b, "\tpkgdesc = %s\n", dotenvSyncDescription)
	fmt.Fprintf(&b, "\tpkgver = %s\n", p.PkgVer())
	fmt.Fprintf(&b, "\tpkgrel = %d\n", p.PkgRel)
	fmt.Fprintf(&b, "\turl = %s\n", dotenvSyncURL)
	fmt.Fprintf(&b, "\tarch = x86_64\n")
	fmt.Fprintf(&b, "\tarch = aarch64\n")
	fmt.Fprintf(&b, "\tlicense = MIT\n")
	fmt.Fprintf(&b, "\tprovides = dotenv-sync\n")
	fmt.Fprintf(&b, "\tconflicts = dotenv-sync\n")
	fmt.Fprintf(&b, "\tconflicts = dotenv-sync-git\n")
	fmt.Fprintf(&b, "\toptions = !strip\n")
	for _, source := range p.CommonSources {
		fmt.Fprintf(&b, "\tsource = %s::%s\n", source.Name, p.resolvedTaggedFileURL(source.Name))
	}
	for _, source := range p.CommonSources {
		fmt.Fprintf(&b, "\tsha256sums = %s\n", source.SHA256)
	}
	for _, target := range p.Targets {
		fmt.Fprintf(&b, "\tsource_%s = %s::%s\n", target.Arch, p.resolvedSourceName(target), p.resolvedSourceURL(target))
		fmt.Fprintf(&b, "\tsha256sums_%s = %s\n", target.Arch, target.SHA256)
	}
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "pkgname = %s\n", dotenvSyncBinPackageName)
	return b.String()
}

func (p DotenvSyncBin) PkgVer() string {
	return strings.TrimPrefix(p.VersionTag, "v")
}

func (p DotenvSyncBin) templateSourceURL(target Target) string {
	return fmt.Sprintf("https://github.com/mikeboiko/dotenv-sync/releases/download/v${pkgver}/ds_v${pkgver}_linux_%s.tar.gz", target.LinuxGOARCH)
}

func (p DotenvSyncBin) templateTaggedFileURL(name string) string {
	return fmt.Sprintf("%s/v${pkgver}/%s", dotenvSyncRawURL, name)
}

func (p DotenvSyncBin) resolvedSourceName(target Target) string {
	return fmt.Sprintf("%s-%s-%s.tar.gz", dotenvSyncBinPackageName, p.PkgVer(), target.Arch)
}

func (p DotenvSyncBin) resolvedTaggedFileURL(name string) string {
	return fmt.Sprintf("%s/%s/%s", dotenvSyncRawURL, p.VersionTag, name)
}

func (p DotenvSyncBin) resolvedSourceURL(target Target) string {
	return fmt.Sprintf("%s/releases/download/%s/%s", dotenvSyncURL, p.VersionTag, release.AssetName(p.VersionTag, "linux", target.LinuxGOARCH))
}

func normalizeSHA256(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

func validateSHA256(value string) error {
	if len(value) != 64 {
		return fmt.Errorf("expected 64 hex characters, got %d", len(value))
	}
	if _, err := hex.DecodeString(value); err != nil {
		return fmt.Errorf("invalid hex digest: %w", err)
	}
	return nil
}
